[project]
name = "simpleformbuilder"
version = "0.1.0"
authors = [
  { name="Guillaume GUGUIN", email="guillaume.guguin@gmail.com" },
]
description = "Simple library to build analytical calculation verification forms."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pint",
    "sympy",
]

[tool.setuptools.packages.find]
include = ["simpleformbuilder*"]